import * as PIXI from 'pixi.js';
import { Ease } from './Easing';
import TweenManager from './TweenManager';
import TweenPath from './TweenPath';
export default class Tween extends PIXI.utils.EventEmitter {
    target: any;
    private _manager;
    private _chainTween;
    private _to;
    private _from;
    private _delayTime;
    private _elapsedTime;
    private _repeat;
    private _pingPong;
    active: boolean;
    time: number;
    easing: Ease;
    expire: boolean;
    repeat: number;
    delay: number;
    loop: boolean;
    pingPong: boolean;
    isStarted: boolean;
    isEnded: boolean;
    path: TweenPath;
    pathReverse: boolean;
    pathFrom: number;
    pathTo: number;
    constructor(target: any, manager?: TweenManager);
    chain(tween?: Tween): Tween;
    start(): Tween;
    stop(): Tween;
    to(data: any): Tween;
    from(data: any): Tween;
    remove(): Tween;
    clear(): void;
    reset(): Tween;
    update(delta: number, deltaMS: number): void;
    _parseData(): void;
    _apply(time: any): void;
    _canUpdate(): boolean;
    manager: TweenManager;
}
